REDDIT_CLIENT_ID = ""
REDDIT_CLIENT_SECRET = ""
USER_AGENT = "User-Agent: DEVICE:NAME:VERSION (by /u/USERNAME)"

EMAIL = "YOUR EMAIL ID"
PASSWORD = "YOU APP SPECIFIC PASSWORD"
MAIL_TO = ["LIST", "OF", "EMAIL", "IDS", "TO", "MAIL"]

KEYSEARCH = {
    'SUBREDDITNAME': ["LIST", "OF", "KEYWORDS"],
    'SUBREDDITNAME2': ["LIST", "OF", "KEYWORDS"],
    'SUBREDDITNAME3': ["LIST", "OF", "KEYWORDS"],
}